### PR TITLE
Fix golint #33

### LINKED ISSUE #33: Fix golint warning
https://goreportcard.com/report/github.com/HuKeping/rbtree#golint

part of #27

### PR DESCRIPTION
**Pull request by u5surf**
Fixes #33 
I fixed all golint warnings. Almost I fixed the comment of expose items.
it might be misunderstanding those exposed func, var...

### CODE REVIEW

File: iterator.go [hunk 1]
```diff
@@ -4,6 +4,7 @@
 
 package rbtree
 
+// Iterator is the function of iteration entity
```
Comment (HuKeping) [inline iterator.go]: we may add a sample to help people to understand the `Iterator` type, how about
```
// Iterator is the function of iteration entity which would be 
// used by those functions like `Ascend`, `Dscend`, etc.
//
// A typical Iterator with Print :
// func loop_with_print(item rbtree.Item) bool {
//         i, ok := item.(XXX)
//         if !ok {
//                 return false
//         }
//         fmt.Printf("%+v\n", i)
//         return true
// }
```

File: rbtree.go [hunk 2]
```diff
@@ -26,10 +28,13 @@ type Node struct {
 }
 
 const (
-	RED   = 0
+	// RED represents the color of the node is red
+	RED = 0
+	// BLACK represents the color of the node is brack
```
Comment (HuKeping) [inline rbtree.go]: typo :) `brack`

File: rbtree.go [hunk 3]
```diff
@@ -26,10 +28,13 @@ type Node struct {
...
 	BLACK = 1
 )
 
+// Item has a method to compare its which is less
```
Comment (HuKeping) [inline rbtree.go]: typo?

File: stats.go [hunk 4]
```diff
@@ -41,6 +43,7 @@ func (t *Rbtree) Delete(item Item) Item {
 	return t.delete(&Node{t.NIL, t.NIL, t.NIL, RED, item}).Item
 }
 
+//Get search the node which includes its node
```
Comment (HuKeping) [inline stats.go]: how about something like
```
// Get search for the specified item (which was carried by a Node)  in the tree, return nil if not found.
```

**Comment by HuKeping** [comment]
Could you please add your   sign-off , the rest LGTM.

```
Signed-off-by: u5surf <xxx@xxx.com>
```
